1> What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code, functions, and modules that extend the capabilities of the Python programming language. 
These libraries provide a set of tools and functionalities to perform specific tasks, making it easier for developers to implement complex features without having to write code
from scratch.

Python libraries serve several purposes, including:

* Code Reusability: Libraries contain reusable code that can be easily integrated into different projects, saving time and effort for developers.
* Modularity: Libraries allow for modular programming, where developers can break down their code into smaller, more manageable components.
* Efficiency: Libraries are often optimized for performance and reliability. By using well-established libraries, developers can benefit from the expertise of others 
  and ensure that their code operates efficiently.
* Rapid Development: Python libraries provide a foundation for rapid development. Developers can focus on implementing the unique aspects of their project while relying on libraries 
  to handle routine or standard tasks.
* Standardization: Some libraries become de facto standards for certain tasks. For example, NumPy and pandas are widely used for numerical and data analysis tasks, respectively. 
  Using such standard libraries helps create consistency and compatibility across different projects.





2> What is the difference between Numpy array and and List?

* Homogeneity:

List: Can contain elements of different data types.
Numpy Array: Requires all elements to be of the same data type, promoting homogeneity.

* Performance:

List: Generally slower for numerical operations and large datasets.
Numpy Array: Designed for numerical operations, providing faster and more efficient computations, especially with large datasets.

* Memory Efficiency:

List: More memory overhead due to the flexibility of storing different data types.
Numpy Array: More memory-efficient due to homogeneous data type storage.
* Syntax and Functionality:

List: Offers more general-purpose functionality, suitable for various tasks.
Numpy Array: Provides specialized functions for numerical operations, array manipulation, and linear algebra.

* Convenience:

List: More convenient for general-purpose tasks and small-scale data.
Numpy Array: More convenient for mathematical and scientific computing involving large datasets.

* Operations:

List: Limited in terms of vectorized operations; often requires explicit looping.
Numpy Array: Supports vectorized operations, enabling element-wise operations without the need for explicit loops.

* Size and Dimension:

List: Can be multi-dimensional but is not optimized for such use cases.
Numpy Array: Specifically designed for multi-dimensional arrays and provides efficient operations on them.

* Creation:

List: Created using square brackets and can be easily extended or modified.
Numpy Array: Created using the numpy.array() constructor and has fixed size upon creation.

3>  Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Find the shape
shape_of_array = my_array.shape

# Find the size
size_of_array = my_array.size

# Find the dimension
dimension_of_array = my_array.ndim

print("Shape of the array:", shape_of_array)
print("Size of the array:", size_of_array)
print("Dimension of the array:", dimension_of_array)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


4>  Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the first row
first_row = my_array[0, :]

print("First row of the array:", first_row)


First row of the array: [1 2 3 4]


5>  How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = my_array[2, 3]

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


6>  Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = my_array[:, 1::2]

print("Odd-indexed elements from the array:")
print(odd_indexed_elements)


Odd-indexed elements from the array:
[[ 2  4]
 [ 6  8]
 [10 12]]


7> How can you generate a random 3x3 matrix with values between 0 and 1?

In [12]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.37798425 0.80850923 0.55995726]
 [0.91906916 0.78184042 0.91555058]
 [0.33249473 0.18807625 0.8739925 ]]


8> Describe the difference between np.random.rand and np.random.randn?

* np.random.rand:

This function generates random values from a uniform distribution over the half-open interval [0.0, 1.0). In other words, it produces random numbers that are uniformly distributed between 0 (inclusive) and 1 (exclusive).
Syntax: np.random.rand(d0, d1, ..., dn), where d0, d1, ..., dn specify the dimensions of the output array.

In [16]:
import numpy as np

random_values = np.random.rand(2, 3)  # Example: Generates a 2x3 array with values between 0 and 1
print(random_values)

[[0.5601027  0.70010053 0.43403384]
 [0.27902304 0.90690029 0.61859605]]


* np.random.randn:

This function generates random values from a standard normal distribution (mean = 0, standard deviation = 1). It produces numbers that are more likely to be close to 0 and less likely to be far from 0, following a bell-shaped curve (normal distribution).
Syntax: np.random.randn(d0, d1, ..., dn), where d0, d1, ..., dn specify the dimensions of the output array.

In [18]:
import numpy as np

random_values_normal = np.random.randn(2, 3)  # Example: Generates a 2x3 array with values from a normal distribution
print(random_values_normal)

[[-0.64092673  0.18813156 -0.4539975 ]
 [-0.977929    0.45901676 -1.31641213]]


9> Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [19]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase dimension along the third axis
increased_dimension_array = np.expand_dims(original_array, axis=2)

print("Original array:")
print(original_array)
print("\nArray with increased dimension:")
print(increased_dimension_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10>  How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [20]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose the array using numpy.transpose
transposed_array = np.transpose(original_array)

# Alternatively, you can use the .T attribute
# transposed_array = original_array.T

print("Original array:")
print(original_array)
print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11>  Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
* Index wise multiplication
* Matrix multiplication
* Add both the matrics
* Subtract matrix B from A
* Divide Matrix B by A

In [21]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Index-wise (element-wise) multiplication
index_wise_multiplication_result = A2 * B2

# Matrix multiplication
matrix_multiplication_result = np.dot(A2, B2.T)  # Assuming you want to multiply A2 by the transpose of B2

# Addition
addition_result = A2 + B2

# Subtraction
subtraction_result = A2 - B2

# Division
division_result = np.divide(B2, A2)

# Print results
print("Index-wise (Element-wise) Multiplication Result:")
print(index_wise_multiplication_result)

print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result)

print("\nAddition Result:")
print(addition_result)

print("\nSubtraction Result:")
print(subtraction_result)

print("\nDivision Result:")
print(division_result)


Index-wise (Element-wise) Multiplication Result:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division Result:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12> Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function used to swap the byte order (endianness) of an array is numpy.ndarray.byteswap().

Here's an example of how you can use it:

In [22]:
import numpy as np

# Create an example array
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap byte order
swapped_array = original_array.byteswap()

# Print the original and swapped arrays
print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[1 2 3 4]

Swapped Array:
[16777216 33554432 50331648 67108864]


13>  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse (or matrix inverse) of a square matrix. The significance of this function lies in its applications, particularly in linear algebra. Here are some key points:

Matrix Inverse:

For a square matrix A, if there exists another matrix B such that the product AB (and BA) is the identity matrix, then B is the inverse of A.
The inverse of a matrix is denoted as 

A 
−1
 .
Solving Linear Equations:

The matrix inverse is often used to solve systems of linear equations of the form 

Ax=B, where A is the coefficient matrix, x is the vector of variables, and B is the vector on the right-hand side.
The solution can be expressed as 

x=A 
−1
 B.
Eigenvalue and Eigenvector Calculations:

The inverse of a matrix is used in the computation of eigenvalues and eigenvectors.
Determinant Calculation:

The inverse of a matrix is related to its determinant. The determinant of a matrix A is nonzero if and only if A has an inverse.
Numerical Stability:

Computing the inverse of a matrix numerically can be sensitive to round-off errors. The np.linalg.inv function in NumPy is implemented using efficient and numerically stable algorithms.

 What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. 

In [23]:
#EXAMPLE

import numpy as np

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2x3 matrix
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


15>  What is broadcasting in Numpy?

In NumPy, broadcasting is a powerful feature that allows operations on arrays of different shapes and sizes without the need for explicit expansion or replication of the smaller array. This implicit behavior of extending the smaller array to match the shape of the larger one during operations is known as broadcasting.

In [ ]:
#E